#==========================================================
#= GestUser Web Service - Versione Base
#==========================================================

# Configurazione del server
server:
  port: 8019  # Porta su cui il servizio sarà in ascolto

# Configurazione dell'applicazione Spring
spring:
  application:
    name: GestUser  # Nome dell'applicazione

  #==========================================================
  #= PARAMETRI DB MONGODB
  #==========================================================
  # Configurazione del database MongoDB
  data:
    mongodb:
      authentication-database: admin  # Database per l'autenticazione
      database: ms-users  # Nome del database utilizzato dall'applicazione
      host: localhost  # Indirizzo del server MongoDB
      password: 123Stella  # Password per l'accesso al database (considerare l'uso di variabili d'ambiente per maggiore sicurezza)
      port: 37017  # Porta del server MongoDB
      username: adiener  # Username per l'accesso al database
      auto-index-creation: true  # Abilita la creazione automatica degli indici

  # Importazione di configurazioni aggiuntive
  config:
    import: classpath:application-secret.yml  # Importa configurazioni sensibili da un file separato